### ISSUE TITLE
As a user who prefer typing over mouse input, I can access all the features of SpongeBob without a mouse, so that I can accomplish tasks faster through typing.

### ISSUE THREAD

**Issue by Zhubo225** [AY1920S1-CS2113T-F11-1/main#97]

**Comment by Tejasvas123** [comment]
Everyone is expected to implement features as per this issue so this issue will be open till v1.4 and will be labelled under status.OnGoing

**Comment by Tejasvas123** [comment]
We are almost done with this so I am closing it.
